### ISSUE TITLE
Flagged As Virus By McAfee Defender Endpoint Protection

### ISSUE THREAD

**Issue by curi0usJack** [rasta-mouse/TikiTorch#1]
Can u fix plz kthx

--NotCuri0usJack

**Comment by rasta-mouse** [comment]
I'll get right on it bro

**Comment by rasta-mouse** [comment]
Close enough 💃 
![mcafee](https://user-images.githubusercontent.com/7346521/53269424-bcd28c00-36e0-11e9-957c-20642ce241db.PNG)
