### ISSUE TITLE
Windows7 Process Hollowing Issue

### ISSUE THREAD

**Issue by fasetto** [rasta-mouse/TikiTorch#12]
It doesn't work on win7 computers. I tested both x86 and x64 pc.
I tried to find the issue, but no luck. Any ideas ?

**Comment by fasetto** [comment]
Maybe the problem is somewhere here ?

https://github.com/rasta-mouse/TikiTorch/blob/729c0be5feb98f9912b4a5da988cc7ae7010f990/TikiLoader/Hollower.cs#L88-L130

**Comment by rasta-mouse** [comment]
No idea, I’m not interested in Windows 7.
