### ISSUE TITLE
No Output from CobaltStrike

### ISSUE THREAD

**Issue by akefallonitis** [rasta-mouse/TikiTorch#2]
I have load the cna script to CS (3.12) but after loading and running go there is no output or any file on http://teamserverip/TikiTorch. Is it tested am i missing something ?

**Comment by rasta-mouse** [comment]
Did you clone the whole repo, or did you only download the CNA?

**Comment by akefallonitis** [comment]
Yes ofcource in a custom path 
![image](https://user-images.githubusercontent.com/24274227/53495284-4949c980-3aa8-11e9-9c57-7907d6822522.png)

**Comment by rasta-mouse** [comment]
My best guess is you'll have to switch the back-slashes for forward-slashes in the calls to `getFileProper`.

**Comment by akefallonitis** [comment]
Yes it worked! Thank you very much for your help
